### PR TITLE
bug: splice index error handle

### PR DESCRIPTION
**Pull request by shohreh-zarkesh**
Hi guys, 

When I follow my application error in my case, I found the error in splice index.

Thanks for the PR!

To better assist you, please select the type of PR you want to create.

Click the "Preview" tab above, and click on the link for the PR type:

- [:bug: Bug fix or new feature](?template=bugfix.md)
- [:memo: Documentation Fix](?template=documentation-edit.md)
- [:book: New/Updated Documentation Content](?template=documentation-new.md)

### CODE REVIEW

**Comment by phryneas** [comment]
It should be impossible that that line of code is ever reached if listener is not in nextListeners.
Can you provide a test that would fail without this change?

**Comment by timdorr** [comment]
This is the same change as #4449, which is not an actual issue.

**Comment by phryneas** [comment]
Pretty much the reason why I copied my comment over from there.

@shohreh-zarkesh we would accept a PR for this if you can prove that this happens - but we really need proof. From reading the code, it should be 100% impossible and never happen.

Does this actually happen to you or do you have another reason to open this PR?

**Comment by markerikson** [comment]
Vaguely related: for Redux 5.0 we should convert `listeners` into a `Set`. We can safely assume ES6 support by now :)

**Pull request closed without merging**
