### PR TITLE
Fixed build script by upgrading rollup-plugin-typescript2 to latest

### PR DESCRIPTION
**Pull request by mayavera**
Howdy! When I tried to run `npm build`, I was seeing the following error:

```
madison ~/projects/redux 
489 ߷  npm run build                     

> redux@5.0.0-alpha.0 build
> rollup -c

Error loading `tslib` helper library.
[!] Error: Package subpath './package.json' is not defined by "exports" in /Users/madison/projects/redux/node_modules/tslib/package.json
Error: Package subpath './package.json' is not defined by "exports" in /Users/madison/projects/redux/node_modules/tslib/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/madison/projects/redux/node_modules/rollup-plugin-typescript2/src/tslib.ts:11:23)
```

It seems like `rollup-plugin-typescript2` is trying to access a file that's not exported by `tslib`. My first attempt at solving it was to update the `rollup-plugin-typescript2` package to see if they fixed the issue and it worked!

```
madison ~/projects/redux 
493 ߷  npm run build                               

> redux@5.0.0-alpha.0 build
> rollup -c


src/index.ts → lib/redux.js...
created lib/redux.js in 3.4s

src/index.ts → es/redux.js...
created es/redux.js in 2s

src/index.ts → es/redux.mjs...
created es/redux.mjs in 2.4s

src/index.ts → dist/redux.js...
created dist/redux.js in 1.5s

src/index.ts → dist/redux.min.js...
created dist/redux.min.js in 2.1s

```

### Changelog

- Fixed a build error by upgrading `rollup-plugin-typescript2` to version `0.31.1`

### CODE REVIEW

**Comment by markerikson** [comment]
And of course this PR has a conflict now that I merged the ESLint PR.

Could you rebase/merge and resolve that conflict?

**Comment by markerikson** [comment]
*sigh*  naturally I shoulda run the build checks on the docs PR too :)

There were a couple of formatting/spacing issues with the `applyMiddleware/bindActionCreators` docs updates. Could you do me a favor, merge `master` into this branch, and then re-run Prettier to make sure everything's formatted right?

Thank you!

**Comment by mayavera** [comment]
@markerikson No worries, I'll fix the conflicts and formatting and push to this branch.

**Comment by mayavera** [comment]
@markerikson Ok, I fixed the merge conflicts with `master`. I opened another PR for formatting the docs as it seems out of scope: https://github.com/reduxjs/redux/pull/4257.

**Comment by markerikson** [comment]
Thanks, merged the formatting PR.  (Personally I've always been fine to smuggle cleanup fixes into whatever I'm working on atm, but this works too.)

Seeing a weird failure with this build now while trying to install packages:

```
npm ERR! @yarn-tool/resolve-package not accessible from rollup-plugin-typescript2
```

Googling suggests that there's now a package versioning mismatch between `package.json` and `package-lock.json`, which is probably due to how the merge conflict got resolved.

**Comment by mayavera** [comment]
@markerikson Ah, sorry about that. I just reset my branch's `package-lock.json` to `master`, then ran a clean `nom install`, then committed the resulting `package-lock.json`. That _should_ to the trick 🤞

**Comment by markerikson** [comment]
Thanks!

**Pull request merged**
