### PR TITLE
Fix Post List image on Part 3 of Essentials Tutorial

### PR DESCRIPTION
**Pull request by jordanmoore753**
---
name: "\U0001F4DD Documentation Fix"
about: Fixing a problem in an existing docs page
---

## Checklist

- [ ] Is there an existing issue for this PR?
  - [Issue](https://github.com/reduxjs/redux/issues/3830)
- [ ] Have the files been linted and formatted?
  - No linting necessary, only repointed a link in markdown and added a `png` file.

## What docs page needs to be fixed?

- **Redux Essentials Tutorial**:
- **Part 3**:

## What is the problem?
The image that should show the working posts list is actually showing an image with the completed navbar and notifications feature.

## What changes does this PR make to fix the problem?
This PR does the following:
- adds `working_post_list.png` to `website/static/img/tutorials/essentials`
- pointed the `part-3-data-flow.md`'s img src to point at the added image mentioned above.

### CODE REVIEW

**Comment by markerikson** [comment]
Looks like there's a formatting issue with the Markdown file.  Can you reformat with Prettier and push?

**Comment by jordanmoore753** [comment]
> Looks like there's a formatting issue with the Markdown file. Can you reformat with Prettier and push?

I checked the file with `--check part-3-data-flow.md` and it said it was formatted correctly. I went ahead and issued `--write part-3-data-flow.md` to hopefully force some change, but the file didn't change in response to the command. Is there another linter I should try running it through? I would commit the prettier-formatted file but Git doesn't recognize any changes so I can't push.

**Comment by markerikson** [comment]
Eh, let's go ahead and put this in, then.

**Comment by jordanmoore753** [comment]
Okay. I scrolled through the updated page on the deployed documentation just to be safe and didn't see any formatting issues. Have a great day!

**Pull request merged**
