### PR TITLE
docs: create "Thinking in Redux" and "Real World Usage" sections

### PR DESCRIPTION
**Pull request by bpas247**
## PR Type

**Does this PR add a _new_ page, or update an _existing_ page?**

- moves around the "Ecosystem", "Core Concepts", "Three Principles", and "Prior Art" page.
- Updates the "Getting Started" page

## Checklist

- [x] Is there an existing issue for this PR?
  - #3594
- [x] Have the files been linted and formatted?

## TODOs

- [x] Add entries to the Netlify `website/_redirects` file
- [x] Ensure that there aren't any more broken links throughout the website due to the pages being moved around

### CODE REVIEW

**Comment by markerikson** [comment]
Great, thanks!  I'll try to look through this in the next couple days.

Note that for any pages that are being moved, we need to add entries to the Netlify `website/_redirects` file to ensure that old external URLs still end up on the right page.  I think there may also be one other reference to the "Ecosystem" page in the "Configuring Your Store" page.

Thinking about this further, I think I'd actually rather split the work into two different PRs.  One should create the "Real World Usage" section and move whatever other pages we want into there.  The other should add the new "Quick Start" page.

**Comment by bpas247** [comment]
> Note that for any pages that are being moved, we need to add entries to the Netlify website/_redirects file to ensure that old external URLs still end up on the right page. I think there may also be one other reference to the "Ecosystem" page in the "Configuring Your Store" page.

Added those items to the TODOs 👍

> Thinking about this further, I think I'd actually rather split the work into two different PRs. One should create the "Real World Usage" section and move whatever other pages we want into there. The other should add the new "Quick Start" page.

Yeah I was thinking about that when I was naming this PR actually 😅 should I go ahead and close this PR and split the work up then?

**Comment by markerikson** [comment]
Eh, pick one side or the other and do that part in this PR :)  Maybe split the "Quick Start" out from this, since it's the smaller piece, and then rename this to "Create 'Real World Usage'" section?

**Comment by bpas247** [comment]
This looks about ready for review 👍

**Comment by timdorr** [comment]
Looks like this aged out. I'd say just redo the PR at this point, since it's diverged so much. Sorry about that!

**Comment by markerikson** [comment]
Yeah. The re-categorization is absolutely still something I want done, but it'd be worth taking some time to plan out what goes where.

**Pull request closed without merging**
