### PR TITLE
fixed typo in redux essential tutorial part-1-overview-concepts

### PR DESCRIPTION
**Pull request by uzlash**
---
name: :memo: Documentation Fix
about: Fixing a problem in an existing docs page
---

## Checklist

- [ ] Is there an existing issue for this PR?
  -  I don't think so
- [ ] Have the files been linted and formatted?
  - Yes
## What docs page needs to be fixed?

- **Section**:
- Tutorials
- **Page**:
- part-1-overview-concepts

## What is the problem?
Just a quick typo fix no problem
## What changes does this PR make to fix the problem?
Changed the array value from d to b

### CODE REVIEW

**Comment by markerikson** [comment]
Hiya, thanks for the PR.  Looking at it, I think the current contents are correct and not a typo.  Thanks anyway!

**Comment by uzlash** [comment]
Hello mark, the content isn't correct because this  is what is in the docs:

const arr = ['a', 'b']
// In the same way, we can change the contents of this array
arr.push('c')
arr[1] = 'd'

and it is supposed to be arr[1] = 'b' and not 'd'

Best regards

**Comment by markerikson** [comment]
That's actually my point.  `'b'` is what's _already_ in the array.  But, this snippet is showing how you can _change_ what's in the array.  In other words, it's intentionally showing "this is how you can overwrite `'b'` with `'d'` instead".

**Comment by uzlash** [comment]
Ohhhh, thank you for the clarification then, I appreciate it.

Warm regards

**Pull request closed without merging**
