### PR TITLE
docs: Fix broken url in docs

### PR DESCRIPTION
**Pull request by saintmalik**
## Summary

Easy Navigation and easy reading for others 

(Fix broken url in MigratingToRedux.md and Troubleshooting.md)

### CODE REVIEW

**Comment by markerikson** [comment]
Tell you what - can you specifically link to the file versions from the `v4.0.5` tag tree instead?

**Comment by saintmalik** [comment]
> Tell you what - can you specifically link to the file versions from the `v4.0.5` tag tree instead?

I don't understand you well, can you explain better what you mean

**Comment by markerikson** [comment]
@saintmalik the file links in there have two issues:

- They're to the TS version of `createStore`, which hasn't actually been published in a real version yet, and might be harder to read for people who aren't familiar with TS
- Since it's pointing to `master`, that file might change at some point in the future

So, it's better to link to a specific version of the file at a known point in history.  In this case, I'm suggesting that we link to the file as it existed when we published the `v4.0.5` tag, which you can link to this way:

https://github.com/reduxjs/redux/blob/v4.0.5/src/createStore.js

**Comment by saintmalik** [comment]
> @saintmalik the file links in there have two issues:
> 
> * They're to the TS version of `createStore`, which hasn't actually been published in a real version yet, and might be harder to read for people who aren't familiar with TS
> * Since it's pointing to `master`, that file might change at some point in the future
> 
> So, it's better to link to a specific version of the file at a known point in history. In this case, I'm suggesting that we link to the file as it existed when we published the `v4.0.5` tag, which you can link to this way:
> 
> https://github.com/reduxjs/redux/blob/v4.0.5/src/createStore.js

Okay, I will do that

**Comment by saintmalik** [comment]
> https://github.com/reduxjs/redux/blob/v4.0.5/src/createStore.js

Done, made the chnages

**Comment by markerikson** [comment]
Thanks!

**Pull request merged**
