### PR TITLE
Replace README Gist with CodeSandbox Example

### PR DESCRIPTION
**Pull request by dan-kez**
Hi All!

Per the request in issue https://github.com/reduxjs/redux/issues/2590#issuecomment-416686948 I added a codesandbox example for the main Redux gist presently on the README.

### CODE REVIEW

**Comment by timdorr** [comment]
Unfortunately, this won't work, as GitHub won't display the iframe and the readme here is fairly high traffic.

**Comment by dan-kez** [comment]
Interesting, I didn't realize that github blocks it but it makes sense in retrospect. I'll pick a different code snippet to embed and link to this codesandbox example in the readme.

**Comment by timdorr** [comment]
Let's not mess with the readme just yet. I'd rather see how it works with a page somewhere inside of the docs. A great place to start would be the examples page, where we already have Codesandbox links: https://redux.js.org/introduction/examples

**Comment by SamyPesse** [comment]
GitBook should support Codesandbox embeds (it uses [iframely.com](https://iframely.com/)).

Since embeds doesn't exist in Markdown, We serialize it as a liquid tag with some JSON (`{% embed data="{\"url\":\" ...`).

## Solution 1: THML Comments for GitBook specific content

One thing that could work, will be for GitBook to support some special HTML comments that will be hidden on GitHub, but visible on GitBook.

Something like (better syntax ideas are welcome):

```
<!--ONLY_GITBOOK
{% embed data="{\"url\":\"https://codesandbox.io/embed/github/reactjs/redux/tree/master/examples/counter\",\"type\":\"link\",\"title\":\"CodeSandbox\",\"description\":\"CodeSandbox is an online editor       tailored for web applications.\",\"icon\":{\"type\":\"icon\",\"url\":\"https://codesandbox.io/favicon.ico\",\"aspectRatio\":0},\"thumbnail\":{\"type\":\"thumbnail\",\"url\":\"https://codesandbox.io/static/img/banner.png\",\"width\":1200,\"height\":630,\"aspectRatio\":0.525}}" %}
ONLY_GITBOOK-->
```

## Solution 2: GitBook should parse iframe tags as embeds

Or the other (probably better) solution will be for GitBook to support iframe HTML tags (not as iframe itself, but as embeds). The iframe will be stripped by GitHub, but the embed will be visible on GitBook.

---

> Also, when I hit save in the Gitbook editor, it created a commit that touched 140 files, including renaming every markdown file in the repo to lowercase and a bunch of other stuff. Not cool. I reverted that.

Yep sorry, I've mentioned a few months ago that you should not edit on the platform since it'll try to normalize the content (we don't store Markdown on our end).

It works well for repositories that started using GitBook from day one, or are using GitBook as the main source of edits. But it results in a massive first commit for documentation like Redux.

**Comment by dan-kez** [comment]
Sorry for being MIA for a bit. The last few weeks have been hectic.

I'm happy to spend some time tonight / this week updating the examples Tim linked above. I can use the liquid tag example that Mark & Samy gave if that's desirable. 

One thing to note, when I ran gitbook locally, the iframe embed did seem to work. If there is a different way I should be testing please let me know!

**Comment by markerikson** [comment]
@dan-kez: yeah, if you can play with this a bit more and see if there's a combo that does work right now, I'd appreciate it.  Thanks!

**Comment by SamyPesse** [comment]
We've just released an improvement for embeds, inserting the following code in the README will show the CodeSandbox on GitBook:

```
{% embed url="https://codesandbox.io/s/zqq52wqj5p" %}
```

**Comment by dan-kez** [comment]
I feel terrible - this totally slipped my mind after I got back from vacation. Happy to hear the update @SamyPesse . I will update this PR today.

**Comment by timdorr** [comment]
Closing this out since we're on Docusaurus now. Feel free to rebuild this for that system, though!

**Pull request closed without merging**
