### PR TITLE
Fix mistake in kindOf.ts

### PR DESCRIPTION
**Pull request by anfengchen**
In function miniKindOf: in other case, forget to invoke 'Object.prototype.toString' to get type

Thanks for the PR!

To better assist you, please select the type of PR you want to create.

Click the "Preview" tab above, and click on the link for the PR type:

- [:bug: Bug fix or new feature](?template=bugfix.md)
- [:memo: Documentation Fix](?template=documentation-edit.md)
- [:book: New/Updated Documentation Content](?template=documentation-new.md)

### CODE REVIEW

**Comment by anfengchen** [comment]
Same as  #4160

**Comment by timdorr** [comment]
Can you fix the formatting so tests can pass?

**Comment by anfengchen** [comment]
@timdorr I'm not familiar with PR. I run 'npm run format' , maybe it will work this time

**Comment by timdorr** [comment]
Can you remove the package-lock.json change? You have an older version of npm installed. This should just be some code changes.

**Comment by anfengchen** [comment]
@timdorr  this time, I think it's OK

**Comment by timdorr** [comment]
Went with #4160 because it was first. Thanks for getting the ball rolling again!

**Pull request closed without merging**
