### PR TITLE
Docs/videos

### PR DESCRIPTION
**Pull request by Christopher-Warren**
---
name: :book: New/Updated Documentation Content
about: Adding a new docs page, or updating content in an existing docs page
---

## PR Type

**Does this PR add a _new_ page, or update an _existing_ page?**
Adds a new page

## Checklist

- [x] Is there an existing issue for this PR?
  - #4354 
- [X] Have the files been linted and formatted?

## What docs page is being added or updated?

- **Section**: 
- **Page**: tutorials/**videos**/

### What kind of content category is this page (tutorial, how-to, explanation, reference)?
Tutorial. added links to external egghead.io videos, and embedded a video with YouTube description with a course summary. All links come from #4354   

### Who is the intended target audience?
Redux beginners and those who wish to modernize legacy Redux with RTK

### CODE REVIEW

**Comment by markerikson** [comment]
Thanks for filing the PR!

For now, I think I'd like to stick with one "Videos" page inside the "Tutorials" category, with each of the recommended courses/videos on one page.  Can you rework it that way?

**Comment by Christopher-Warren** [comment]
Sure thing!


> For now, I think I'd like to stick with one "Videos" page inside the "Tutorials" category, with each of the recommended courses/videos on one page. Can you rework it that way?

**Comment by Christopher-Warren** [comment]
Hello @markerikson, I added "Videos" as it's own separate page. The markup is quite simple. 

Please bear with me as I am somewhat new to contributing to open source. 😅

If the latest commit totally misses the mark, feel free to close the pull request.

**Comment by markerikson** [comment]
I tweaked the descriptions a bit, and merged.  Thanks for helping add this!

**Pull request merged**
