### PR TITLE
Fix MiddleWare.md typo

### PR DESCRIPTION
**Pull request by jhaenchen**
grok isn't a word :)

### CODE REVIEW

**Comment by timdorr** [comment]
It is: https://en.wikipedia.org/wiki/Grok

**Comment by jhaenchen** [comment]
@timdorr  That's cute and all but maybe we should use words that people actually understand instead of le cute easter eggs in technical docs?

**Comment by timdorr** [comment]
It's not an easter egg. It's a word: https://www.merriam-webster.com/dictionary/grok https://en.oxforddictionaries.com/definition/grok

**Comment by jhaenchen** [comment]
It’s a cutesy developer word that requires someone who learned normal English to look up. It has no place in a technical document.

Jackson "Jake" Haenchen
Jacksonhaenchen@gmail.com
832-423-3342
________________________________

**Pull request closed without merging**
