### PR TITLE
Add "Create a React Redux App" to getting started

### PR DESCRIPTION
**Pull request by nickmccurdy**
---
name: "\U0001F4D6 New/Updated Documentation Content"
about: Adding a new docs page, or updating content in an existing docs page
---

## PR Type

**Does this PR add a _new_ page, or update an _existing_ page?**

Update an existing page

## Checklist

- [ ] Is there an existing issue for this PR?
  - _link issue here_
- [x] Have the files been linted and formatted?

## What docs page is being added or updated?

- **Section**: Introduction
- **Page**: Getting Started with Redux

### What updates should be made to the page?
Link to the `cra-template-redux` package with a short description and usage information

### Do these updates change any of the assumptions or target audience? If so, how do they change?
This section assumes the user is making a new app with React and Create React App, though the other sections are still usable for other use cases

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Follow up: (interested in opinions on this too)
- Consider adding to Installation page (especially for users that skip to it via a permalink)
- Add to Redux Toolkit's Quick Start page after Installation
- Consider adding to React Redux's Quick Start page after Installation

**Comment by markerikson** [comment]
Looks good.  Longer-term, I'm not sure how to split instructions between "Getting Started" and "Installation".

**Comment by nickmccurdy** [comment]
Do you think I should copy this to the installation pages short-term, or would you rather wait on an additional link in the Redux docs until after the rework?

**Comment by markerikson** [comment]
Sure, let's do that for consistency.

**Pull request merged**
