### PR TITLE
Increased performance of combineReducer result function

### PR DESCRIPTION
**Pull request by whiteand**
---
name: "Improvements of performance of combineReducer and combineReducer's result"
about: Improvements of performance of combineReducer and combineReducer's result
---

### Does this PR add a new _feature_, or fix a _bug_?

It's just a refactoring with improvements of performance

### Why should this PR be included?

It's not necessary to check errors in a positive case on each call to function combination.
I do not know which kind of issue I should create for this improvement. Because this is not a bug.

## Checklist

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Is there an existing issue for this PR?
  - _link issue here_
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated to match the changes in the PR?
- [x] Have the tests been updated to match the changes in the PR?
- [x] Have you run the tests locally to confirm they pass?

It's not a new feature or bugfix. So I do not know what to write here.

### CODE REVIEW

**Comment by timdorr** [comment]
Does this have any measurable performance improvement?

**Comment by whiteand** [comment]
> Does this have any measurable performance improvement?

No, I do not did measurements. Is it not clear that 

```javascript
function f() {
  // code
}
```

is faster than

```javascript
function f() {
  if (someError) {
    throw someError
  }
 // code as in the example above
}
```

**Comment by whiteand** [comment]
Also I think that this code is not optimal:

```javascript
for (let i = 0; i < arr.length; i++) {
  const elem = arr[i]
  if (typeof elem === 'undefined') {
     // something
  }
  if (typeof elem === 'function') {
   // something else
  }
}
```
It should be slower than:
```javascript
for (let i = 0; i < arr.length; i++) {
  const elem = arr[i]
  if (typeof elem === 'undefined') {
     // something
    continue
  }
  if (typeof elem === 'function') {
   // something else
  }
}
```

If `arr` will contain N `undefined` elements. We will not execute `if (typeof elem === 'function')` N times.

**Comment by timdorr** [comment]
combineReducers shouldn't be called that often. If it's your bottleneck, you have other issues. I'm only seeing a 7% difference in my system. It's not really worth changing right now. Thanks anyways!

**Comment by whiteand** [comment]
> combineReducers shouldn't be called that often. If it's your bottleneck, you have other issues. I'm only seeing a 7% difference in my system. It's not really worth changing right now. Thanks anyways!

The main improvement was not about improvement of combineReducer performance But about improvement of performance of reducer created by combineReducer (That is called after each action dispatch)

Thank you for your, review.

**Pull request closed without merging**
