### PR TITLE
Add og:image and twitter:image

### PR DESCRIPTION
**Pull request by 38elements**
---
name: "\U0001F4D6 New/Updated Documentation Content"
about: Adding a new docs page, or updating content in an existing docs page
---

## PR Type

**Does this PR add a _new_ page, or update an _existing_ page?**

This updates an existing page.

## Checklist

- [ ] Is there an existing issue for this PR?
  - _link issue here_
- [ ] Have the files been linted and formatted?

## What docs page is being added or updated?

- **Section**:
- **Page**:

## For Adding New Content

This adds og:image and twitter:image
https://v2.docusaurus.io/docs/theme-classic/#meta-image

### CODE REVIEW

**Comment by timdorr** [comment]
This should use `redux-logo-landscape.png`, which is already the right size for an opengraph image.

**Comment by 38elements** [comment]
@timdorr 
Thank you for reviewing.
I changed image.

**Comment by timdorr** [comment]
Thanks!

**Comment by markerikson** [comment]
@38elements Thanks! Could you also update both the React-Redux and Redux Toolkit repos to use the same image?  I've noted that the RTK repo in particular is using _some_ image, but a recent change to Docusaurus made it so that previews on some sites (like Discord) end up with a _huge_ image preview.

**Comment by 38elements** [comment]
@markerikson 
I think the cause is that the image is not an aspect ratio of 2:1.
I sent pull request.

**Comment by markerikson** [comment]
So I actually tried pasting that PR preview link into Discord, and it looked the same. I think it's something about Docusaurus's generation and Discord's previews.  

It's kind of annoying, since I know that Discord previews of some of the Redux docs _used_ to use a smaller image, and I think this got started after a relatively recent Docusaurus release (alpha.56 or so?)

**Comment by 38elements** [comment]
I know the old image is too zoom in twitter card.
I confirm that the image is works normally in twitter card.
https://cards-dev.twitter.com/validator
Discord may be caching the old image.

**Comment by markerikson** [comment]
Hmmm. So actually, looking at that validator, neither the Redux or RTK previews look very good now.  The sides of the image are cut off.  Are you seeing that too?

**Comment by 38elements** [comment]
Yes, the image is display well in twitter card.
I am sorry.
I don't know much about Discord.

**Comment by 38elements** [comment]
I adjusted the position of the logo and letters.
I changed the size of the image.
Twitter only shrinks the image.

**Pull request merged**
