### PR TITLE
Type-check tests

### PR DESCRIPTION
**Pull request by Methuselah96**
In https://github.com/reduxjs/redux/pull/4487 we switched from ts-jest (which runs type-checking on test files) to Vitest (which does not).

This PR runs type-checking on the tests to make sure they pass.

### CODE REVIEW

**Comment by markerikson** [comment]
Hmm. Apparently the optimization I added / copied that tries to skip tests if there are no `src` changes is skipping the tests here too :(

While you're at it, can you try tweaking the condition to run if there's changes to `.github`?

Worst case, just kill the condition and always run the tests for now.

**Comment by Methuselah96** [comment]
Odd test failure for TypeScript 4.1. I'll take a look later.

**Comment by Methuselah96** [comment]
rxjs types only support >=4.2 👀 

```
  "name": "rxjs",
  ...
  "typesVersions": {
    ">=4.2": {
      "*": [
        "dist/types/*"
      ]
    }
  },
```

**Comment by Methuselah96** [comment]
I think we're good to drop testing against TypeScript 4.1? It [came out on 11/19/20](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/) so it's more than the 2-year support window [defined by DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped#support-window).

**Comment by markerikson** [comment]
Yep, absolutely!  We've generally done rolling TS version compat in our minor releases anyway, so let's drop 4.1 from the test matrix.  (Might as well add 5.0-beta while we're at it?)

**Pull request merged**
