### PR TITLE
3605 Removing broken storify link from docs

### PR DESCRIPTION
**Pull request by r3dm1ke**
Since storify link is broken and twitter thread is not relevant anymore, removed both links and adjusted the description.

### CODE REVIEW

**Comment by r3dm1ke** [comment]
Fixes #3619

**Comment by markerikson** [comment]
Thanks!

**Comment by markerikson** [comment]
Can you fix the formatting with Prettier first?

**Comment by r3dm1ke** [comment]
> 
> 
> Can you fix the formatting with Prettier first?

I just ran the `prettier --list-different "{src,test}/**/*.{js,ts}" index.d.ts "**/*.md"` at the root of the project, it made no changes and returned without an error. Is there another script that is used or maybe a bug in the CI build?

**Comment by markerikson** [comment]
Mmm... no, that's the command, and it's definitely `LearningResources.md` that's busted.

Not sure what the issue is here.

**Comment by timdorr** [comment]
Just run `npm run format` to fix it.

**Comment by markerikson** [comment]
Thanks!

**Pull request merged**
