### PR TITLE
TypeScript: Resolve TS extensions with node-resolve plugin

### PR DESCRIPTION
**Pull request by nickmccurdy**

### CODE REVIEW

**Comment by nickmccurdy** [comment]
@cellog Please take a look, this allows files other than `index.ts` to use the `.ts` extension, without using the TypeScript plugin.

**Comment by cellog** [comment]
this is great! I'll close mine

**Comment by cellog** [comment]
unfortunately, this does not work. the `CommonJS` and `ES` builds do not use `nodeResolve`, so I am going to re-open the other PR that uses the typescript plugin

**Comment by nickmccurdy** [comment]
I added it to all confirmations, so it should work. What’s the use case that’s failing?

**Comment by cellog** [comment]
> I added it to all confirmations, so it should work. What’s the use case that’s failing?

The use case where I hand-copied to my own PR without adding it to the first 2 🤣

I'll sit down over there...

**Comment by nickmccurdy** [comment]
Ah ok, so this is ready to merge?

**Comment by cellog** [comment]
from my seat, this works as advertised, yes

**Comment by nickmccurdy** [comment]
@timdorr Would you mind merging? Thanks!

**Pull request merged**
