### PR TITLE
docs: information about ngrx-entity-relationship

### PR DESCRIPTION
**Pull request by satanTime**
---
name: :book: New Documentation Content
about: adding content in an existing docs page about an ORM lib
---

## PR Type

**this PR updates an "Managing Normalized Data" page**

## Checklist

- [ ] Is there an existing issue for this PR?
  - _link issue here_
- [x] Have the files been linted and formatted?

## What docs page is being added or updated?

- **Section**: Other Approaches
- **Page**: https://redux.js.org/recipes/structuring-reducers/updating-normalized-data#other-approaches
- **Updated Content**: https://github.com/satanTime/redux/blob/docs/ngrx-entity-relationship/docs/recipes/structuring-reducers/UpdatingNormalizedData.md#ngrx-entity-relationship

### What kind of content category is this page (tutorial, how-to, explanation, reference)?
reference with a short explanation

### Who is the intended target audience?
devs who want to select entities with their related entities via single selectors

#### What knowledge are we assuming they have?
novice, they should follow step by step to achieve desired behavior

### What are the intended results or takeaways from reading this page?
devs should know that ORM in Redux isn't as hard as other devs usually say

### What is the most critical info they should learn?
the take away is that selecting related entities is possible and there are libraries for that

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks, but this library appears to be fairly new and not yet a common choice for users. I'd like to get away from specific recommendations, but Redux ORM is still fairly popular at this point. We should probably rewrite this page entirely, but that's for another issue.

**Comment by satanTime** [comment]
Hi @timdorr, thanks for the info. 

I've expected something like that and understand your point.
Might you tell me, what should happen or be achieved to revise this PR in future?

**Comment by markerikson** [comment]
Per Tim's comment, I don't think this is something we would want to feature in the docs specifically.  However, please feel free to submit a PR to list it over in the Redux Addons Catalog at https://github.com/markerikson/redux-ecosystem-links .

**Comment by satanTime** [comment]
Aha, a cool hint, thanks! I'll do!

**Comment by satanTime** [comment]
Hi @timdorr and @markerikson,

would it fit to create a PR for https://redux.js.org/introduction/ecosystem?

Currently I'm working on a PR for https://github.com/markerikson/redux-ecosystem-links

**Pull request closed without merging**
