### PR TITLE
[ISSUE_TEMPLATE] Replace new issue button with community link

### LINKED ISSUE #3712: Can't Dispatch Redux Action From Outside of Component (With Preloaded State)
Hello! I am having an issue where I am unable to dispatch actions from outside of a component. I have found many other people with this issue, but it seems that someone always submits an answer assuming that the "createStore" file always returns a store object:

- https://stackoverflow.com/questions/45043219/calling-dispatch-function-from-a-blank-javascript-file
- https://stackoverflow.com/questions/38460949/what-is-the-best-way-to-access-redux-store-outside-a-react-component
- https://stackoverflow.com/questions/56498212/dispatching-a-redux-thunk-action-outside-of-a-react-component-with-typescript

However, my createStore file looks like this:
```
import { composeWithDevTools } from 'redux-devtools-extension';
import combinedReducers from './reducers/root-reducer';
import { load, save } from 'redux-localstorage-simple';
import { createStore, applyMiddleware } from 'redux';
import todosCustomMiddleware from './middlewares/todosCustomMiddleware';
import loginCustomMiddleware from './middlewares/loginCustomMiddleware';
import socketManager from './middlewares/socketManager';
import { ILoginState } from './reducers/login';
import { ITodosState } from './reducers/todos';
export interface IState {
  loginReducer: ILoginState,
  todosReducer: ITodosState
}
export default (preloadedState: IState) => {
  return createStore(
    combinedReducers,
    getLoadedState(preloadedState),
    composeWithDevTools(
      applyMiddleware(
        save({ states: ['loginReducer'] }),
        todosCustomMiddleware(),
        loginCustomMiddleware(),
        socketManager()
      )
    ),
  );
};
const getLoadedState = (preloadedState: IState | any) => {
  if (typeof window !== 'undefined')
    return {
      ...preloadedState,
      ...load({ states: ['loginReducer'], disableWarnings: true }),
    }
  return {
    ...preloadedState,
  }
}
```
And so then when I try to import it and call "dispatch" like this:
```
import store from './../state/createStore'
store.dispatch(loginSuccess())
```
Then the event is never handled by my middlewares/reducers, and I also get this typescript error:

`Property 'dispatch' does not exist on type '(preloadedState: IState) => Store<{ loginReducer: ILoginState; todosReducer: { fetching: boolean; error: undefined; todos: any; } | { fetching: boolean; error: any; todos: never[]; }; }, AnyAction> & { ...; }'.`

Is there any way for me to dispatch actions from outside of a component when I am syncing the state with localstorage? Thanks!

### PR DESCRIPTION
**Pull request by ryota-murakami**
close #3712

### CODE REVIEW

**Comment by timdorr** [comment]
What might work best is if we break out a separate support page in the docs and model it after [this page](https://github.com/reactjs/reactjs.org/blob/master/content/community/support.md) in the React docs. Then just link to that.

**Comment by ryota-murakami** [comment]
@timdorr Thank you for improve link destination.
I think [this page](https://redux.js.org/introduction/getting-started/#help-and-discussion) is perfect! 👌

**Comment by timdorr** [comment]
No prob, Bob. 

Let's get this in now and we can worry about that page later.

**Comment by ryota-murakami** [comment]
Sure!
I've just browsed new issue page and jumped link destination, that's working correctly.

**Comment by markerikson** [comment]
Sweet, thanks!

**Pull request merged**
