### PR TITLE
Modify: optimize compose，support more args

### PR DESCRIPTION
**Pull request by maquannene**
```
const logger1 = (next, ctx) => action => {
    console.log(ctx);
    console.log('logger1 >>>')
    next(action)
    console.log('logger1 <<<')
}

const logger2 = (next, ctx) => action => {
    console.log(ctx);
    console.log('logger2 >>>')
    next(action)
    console.log('logger2 <<<')
}

const dispose = action => {
   console.log(action)
}

const compose = funcs => {
   return funcs.reduce((a, b) => (next, ...rest) => a(b(next, ...rest), ...rest))
}

const newDispose = compose([logger1, logger2])(dispose, 'ctx')
newDispose('action')
```

middleware function can support more agrs by…rest.

### CODE REVIEW

**Comment by markerikson** [comment]
Appreciate the PR, but there's no reason to make changes to `compose` at this time.

**Comment by maquannene** [comment]
Sorry, Maybe I can not agree.
Some times, i need some `context` in every middleware, it  need pass all agrs to every middleware.

In origin code, 
```
a(b(...args))
```
function `a` just receive one arg, but b receive all args, params not equal i every middleware, so maybe i think it is a bug.

**Comment by maquannene** [comment]
> Appreciate the PR, but there's no reason to make changes to `compose` at this time.
Sorry, Maybe I can not agree.
Some times, i need some context in every middleware, it need pass all agrs to every middleware.

In origin code,

a(b(...args))
function a just receive one arg, but b receive all args, params not equal i every middleware, so maybe i think it is a bug.

**Comment by maquannene** [comment]
> Appreciate the PR, but there's no reason to make changes to `compose` at this time.


Sorry, Maybe I can not agree.
Some times, i need some context in every middleware, it need pass all agrs to every middleware.

In origin code,

a(b(...args))
function a just receive one arg, but b receive all args, params not equal i every middleware, so maybe i think it is a bug.

**Pull request closed without merging**
