### PR TITLE
Add Expo and React Native examples to CI

### PR DESCRIPTION
**Pull request by aryaemami59**
**This PR**:

  - [X] Adds Expo and React Native examples to CI workflow.

### CODE REVIEW

**Comment by timdorr** [comment]
Can we add any caching to this to speed things up? This slows the test suite by nearly 5x and this library isn't React-specific. This seems like overkill to me.

**Comment by aryaemami59** [comment]
@timdorr Sure I can figure out some sort of caching to speed this up.

**Comment by timdorr** [comment]
Updated the RN examples upstream to be much much faster, but also added a cache. Thanks for getting this together!

**Comment by aryaemami59** [comment]
@timdorr

> Updated the RN examples upstream to be much much faster, but also added a cache. Thanks for getting this together!

That's awesome, thank you Tim! This makes me wonder, would it be okay then to re-open https://github.com/reduxjs/redux-thunk/pull/365?

**Comment by timdorr** [comment]
Unfortunately, I can't reopen this PR. But feel free to submit a new one and we'll get it merged in.

**Comment by aryaemami59** [comment]
@timdorr Thank you!!!

**Comment by EskiMojo14** [comment]
i reopened it 👍🏻

**Comment by aryaemami59** [comment]
@EskiMojo14 Thank you Ben!

**Pull request merged**
