### PR TITLE
3075 add historical context

### PR DESCRIPTION
**Pull request by monicatie**
Hi! I took a stab at issue 3075 (https://github.com/reduxjs/redux/issues/3075) 

I read over Mark's links and docs and tried to condense as much of the information into a factual, easily digestible format and limited it to core context pieces. I definitely cut a lot of content in doing so, and can imagine adding some back for more info.

I decided to limit the historical context to three things: Flux, influence of functional paradigms and a philosophy of keeping things simple. These were the main influences I found to have the most historical impact on the React/JS community over the past few years and in my own year long investigation into comparing/contrasting state management libraries in my professional work.

I hope this at least gives a starting point to adding Historical Context for those looking to understand the background. Looking forward to discussing it with you all and making updates.

### CODE REVIEW

**Comment by markerikson** [comment]
Great, thanks!  Busy with some other things atm, but I'll make sure to come back and look at this shortly.

**Comment by monicatie** [comment]
Thanks Mark!

**Comment by monicatie** [comment]
Hi, just wanted to ping.

**Comment by markerikson** [comment]
Hah, sorry, looks like I forgot this PR was here :)

Ah... glancing at it, the immediate issue is that there's no pointer to this in the docs sidebar, so it's not showing up anywhere.  Can you add an entry to put it under the "Other" category for now?

**Comment by monicatie** [comment]
Oh! Sure thing, I'll submit an update

**Comment by monicatie** [comment]
Ah I vaguely remembered this context coming up in relation to the Motivation and Prior Art intro chapters, so I grouped it right before Prior Art to make it chronological and transition into Prior Art.

**Comment by markerikson** [comment]
Tell you what.  We're about to start a major revamp and reorganization of the Redux core docs (see #3313 ).  I'm going to hold off on merging this for the moment.  Once we've nailed down what the revised docs structure should be, we can slot it in with the rest of the changes.

**Comment by monicatie** [comment]
Sounds good!

**Pull request closed without merging**
