### PR TITLE
Reorder installation sections and update readme for consistency

### PR DESCRIPTION
**Pull request by nickmccurdy**
---
name: "\U0001F4D6 New/Updated Documentation Content"
about: Adding a new docs page, or updating content in an existing docs page
---

Recreating #3731 with merge conflicts of moving documentation fixed

## PR Type

**Does this PR add a _new_ page, or update an _existing_ page?**

Update readme and existing pages

## Checklist

- [ ] Is there an existing issue for this PR?
  - _link issue here_
- [x] Have the files been linted and formatted?

## What docs page is being added or updated?

Both the readme and:
- **Section**: Introduction
- **Page**: Getting Started and Installation

### What updates should be made to the page?
Reorder installation sections and update readme for consistency

### Do these updates change any of the assumptions or target audience? If so, how do they change?
No, just keeps documentation more consistent with the readme and other Redux ecosystem packages

### CODE REVIEW

**Comment by markerikson** [comment]
Mmm... not sure we actually want to put the CRA template first on the list here.

**Comment by timdorr** [comment]
Yeah, that's not installation, that's scaffolding.

**Comment by nickmccurdy** [comment]
Perhaps we could have a CRA/template/scaffolding heading instead of putting it under installation? I see your point, but I think it's probably a better starting point for beginners than the usual installation instructions if we can find a good way to communicate it.

**Comment by markerikson** [comment]
I think this is okay as-is for now.

**Pull request closed without merging**
