### PR TITLE
Update devtools extension npm install guide

### PR DESCRIPTION
**Pull request by DuBento**
Thanks for the PR!

To better assist you, please select the type of PR you want to create.

Click the "Preview" tab above, and click on the link for the PR type:

- [:bug: Bug fix or new feature](?template=bugfix.md)
- [:memo: Documentation Fix](?template=documentation-edit.md)
- [:book: New/Updated Documentation Content](?template=documentation-new.md)

### CODE REVIEW

**Comment by markerikson** [comment]
Actually, I think as of the recent DevTools 3.0 release, it's now a separate scoped package name, per https://github.com/reduxjs/redux-devtools/releases/tag/remotedev-redux-devtools-extension%403.0.0 and https://github.com/reduxjs/redux-devtools/pull/948/files#diff-46ac21909169cd3c3c528d28cca98e1fb32578556269dd06149c3ddb95e95ce2 .

Could you update the PR to match that?

**Comment by Methuselah96** [comment]
Note that `redux-devtools` is now `@redux-devtools/core` and that `redux-devtools-extension` is now `@redux-devtools/extension`. I'm guessing that this should should refer to `@redux-devtools/extension`, but I'm not certain.

**Comment by DuBento** [comment]
> Note that `redux-devtools` is now `@redux-devtools/core` and that `redux-devtools-extension` is now `@redux-devtools/extension`. I'm guessing that this should should refer to `@redux-devtools/extension`, but I'm not certain.

I think you are correct. Updated patch.

**Comment by timdorr** [comment]
@DuBento I believe it's supposed to be `@redux-devtools/core` now.

**Comment by Methuselah96** [comment]
It seems a little out-of-place and outdated to recommend installing `@redux-devtools/core` without any context on how to use it (and to say "Most likely, you'll also need the React bindings and the developer tools."). It seems to me that `@redux-devtools/extension` should be the recommended way to use the developer tools.

**Comment by DuBento** [comment]
> @DuBento I believe it's supposed to be `@redux-devtools/core` now.

Since I was just looking for extension support, `/extension` made more sense at the time. But to keep consistent with what was previously in the installation guide maybe I could change to `@redux-devtools`.
Also since someone is mainly looking for the extension support there could be a note suggesting to install only `@redux-devtools/extension`. Could also use your thoughts on the matter @Methuselah96.

**Pull request closed without merging**
