### PR TITLE
Fix docs formatting

### PR DESCRIPTION
**Pull request by markerikson**

### CODE REVIEW

**Comment by timdorr** [comment]
The formatting is handled by prettier. If you've got a problem with it, take it up with them :)

**Comment by markerikson** [comment]
That's actually exactly the issue.  I just merged #3402 , and forgot to check Travis first.  That PR has some bad formatting in it or something, so technically Travis is failing due to Prettier complaining.

But, when I check out master and run Prettier myself, it fixes some _different_ files, these the one from that PR isn't touched, and this branch _still_ fails.  

So, there's some kind of mismatch.

**Comment by timdorr** [comment]
Are you running the latest version of Prettier?

**Comment by markerikson** [comment]
Hmm.  Haven't updated the installed packages in my clone of this repo for a while.

Let's see how it looks now.

**Comment by markerikson** [comment]
That seems to be better.

**Pull request merged**
