### PR TITLE
Move Configuring Your Store to new Real World Usage section

### PR DESCRIPTION
**Pull request by emgoto**
## PR Type

**Moves existing page**

## Checklist

- [x] Is there an existing issue for this PR?
  - #3596 
- [ ] Have the files been linted and formatted?
No -  I don't see any instructions for linting in `website/readme.md`.

## What docs page is being added or updated?
- **Section**:
New Section - "Real World Usage"
- **Page**:
Moved page "Configuring Your Store" to this new "Real World Usage' section.

## Issues
I updated the `_redirects` file too. Unfortunately I wasn't able to get this branch hosted on Netlify to test my changes - ran into some issues:

```
Different publish path detected, going to use the one specified in the Netlify configuration file: 'website/website/build' versus 'build' in the Netlify UI
...
Failed during stage 'building site': Deploy directory 'website/website/build' does not exist
```
I also couldn't get Docusaurus running locally, I switched to the latest version and killed `node_modules`, and that fixed my problem.

### CODE REVIEW

**Comment by markerikson** [comment]
Thanks, appreciate the PR.

That said, I feel like we ought to try to nail down a master plan of what's going to get moved where and what we want the final structure of this new section to look like before we actually pull the trigger on moving things.

Maybe we can discuss this over in #3596 ?

**Comment by emgoto** [comment]
Ah, my bad! I assumed the list of checklist items were ready to go. I can close off this PR for now.

**Comment by markerikson** [comment]
I'd kinda sketched out a general idea of things, but it's been a long time since I wrote that out.  I just don't want to end up having to move the same pages 2-3 different times :)

I'm definitely happy to chat with you and figure out exactly what ought to get moved where.

**Comment by markerikson** [comment]
@emgoto I'd still be happy to have you help figure out how we ought to organize the "Real World Usage" section - let me know if you're interested!

**Pull request closed without merging**
