### PR TITLE
Add ".idea" folder to .gitignore

### PR DESCRIPTION
**Pull request by deepfunc**
It is generated by JetBrains IDEs.

### CODE REVIEW

**Comment by timdorr** [comment]
No, this belongs in your global gitignore file. We don't require the use of JetBrains IDEs, so we shouldn't make affordances for it at the project level.

**Comment by deepfunc** [comment]
I think if someone like me using JetBrains IDEs to clone and open this project, will see ".idea" folder is untracked in git status. After all, not everyone should set it in global gitignore file. :)
Like this repository: [https://github.com/facebook/react/blob/master/.gitignore](https://github.com/facebook/react/blob/master/.gitignore)
@timdorr

**Comment by timdorr** [comment]
Yes, you absolutely should. If you use that IDE, you should ignore it. It doesn't belong in any repo.

**Comment by deepfunc** [comment]
> Yes, you absolutely should. If you use that IDE, you should ignore it. It doesn't belong in any repo.

react, angular, webpack, TypeScript, bootstrap, electron, and more repositories set it in own gitignore file.
Why?

**Pull request closed without merging**
