### PR TITLE
propose typo changes in the title

### PR DESCRIPTION
**Pull request by nitinajaydixit**
- [:memo: Documentation Fix](?template=documentation-edit.md)

### CODE REVIEW

**Comment by phryneas** [comment]
It's not a typo. The page explains "Why Redux Toolkit the [the way] how to use Redux today".

**Comment by nitinajaydixit** [comment]
> It's not a typo. The page explains "Why Redux Toolkit the [the way] how to use Redux today".

Oh, I felt like there's some grammatical mistake like it should be `Why Redux Toolkit is & How To Use Redux Today` or `What Redux Toolkit is & How To Use Redux Today' but reading `Why Redux Toolkit is How To Use Redux Today`  without conjunction 'and' or with punctuation (comma ',') like "Why Redux Toolkit is, How To Use Redux Today" felt awkward. Maybe because I'm a non-native English speaker.

**Comment by markerikson** [comment]
I agree the title feels a bit awkward grammatically, but it's the best we could come up with.  Thanks anyway!

**Comment by nitinajaydixit** [comment]
> I agree the title feels a bit awkward grammatically, but it's the best we could come up with. Thanks anyway!

Alright, I'll look forward to making more meaningful contributions in the future 🤓 🙌🏻

**Pull request closed without merging**
