### PR TITLE
improve performance of ensureCanMutateNextListeners

### PR DESCRIPTION
**Pull request by artalar**
Small improvements for preventing unnecesary calls of `ensureCanMutateNextListeners`

### CODE REVIEW

**Comment by artalar** [comment]
CI failing is not my fault 👀

**Comment by markerikson** [comment]
Fixed the formatting issue on `master`.

How exactly does the change here improve performance?  What benchmarks have you run to see if there's an improvement?

**Comment by artalar** [comment]
Currently `currentListeners.slice()` calls at each `dispatch`, but it is unnecesary if it dispatch is not nesting. It is correct?

**Comment by artalar** [comment]
@markerikson I writing some simple [benchmarks.](https://github.com/artalar/redux/blob/artalar/perf-improves-bench/bench/index.js) It checks exactly the case solved by this PR - subscribe / unsubscribe after each dispatch.

изображение

**Comment by timdorr** [comment]
Finally sat down to look through this. I don't think it really warrants the complexity increase for a 0.3 millisecond speed boost. I'd rather make things easier to read in this case. Thanks anyways for looking at it!

**Pull request closed without merging**
