### PR TITLE
fix typescript config for rollup

### PR DESCRIPTION
**Pull request by cellog**
This allows files other than `index.ts` to be in typescript

### CODE REVIEW

**Comment by nickmccurdy** [comment]
As far as I'm aware, we don't need this since the existing Rollup config in `ts-conversion` already compiles TypeScript to JavaScript. Types can be checked with `npm install`, `npm publish`, or `npm run check-types`.

**Comment by cellog** [comment]
as much as I would like to not need this, rollup does not recognize `import 'blah'` if `blah` is in `blah.ts` (feel free to prove me wrong, I would much rather not have to do this)

**Comment by nickmccurdy** [comment]
I fixed this by using `rollup-plugin-node-resolve`: https://github.com/reduxjs/redux/pull/3517

**Comment by cellog** [comment]
closing as obsolete, thanks @nickmccurdy !

**Comment by cellog** [comment]
re-opening, the fix doesn't quite work as the ES and CommonJS builds don't use `nodeResolve`

**Comment by cellog** [comment]
bye again

**Pull request closed without merging**
