### PR TITLE
Migrate to yarn workspaces

### PR DESCRIPTION
**Pull request by mWaldbaur**
### Does this PR add a new _feature_, or fix a _bug_?

Feature

### Why should this PR be included?

It makes development experience better.

## Checklist

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Is there an existing issue for this PR?
  - _link issue here_
- [x] Have the files been linted and formatted?
- [x] Have the docs been updated to match the changes in the PR?
- [x] Have the tests been updated to match the changes in the PR?
- [x] Have you run the tests locally to confirm they pass?

## New Features

This PR makes the examples use yarn instead of NPM.

### CODE REVIEW

**Comment by markerikson** [comment]
We don't actually have any subpackages in here that would need workspaces. What are you trying to work on?

**Comment by mWaldbaur** [comment]
> We don't actually have any subpackages in here that would need workspaces. What are you trying to work on?

Sorry, I should have explained this in the PR description. I turned the examples into workspaces. This allows them to be treated as workspaces, meaning they can use yarn and can be tested easily.

**Comment by markerikson** [comment]
Honestly, most of those examples are obsolete and need to be rewritten or deleted.

We also _don't_ want to generally install them when you clone the repo and set it up.

What's the background on this effort?

**Comment by mWaldbaur** [comment]
> Honestly, most of those examples are obsolete and need to be rewritten or deleted.
> 
> We also _don't_ want to generally install them when you clone the repo and set it up.

Oh, okay. I was not aware of that.

> What's the background on this effort?

I was just looking for an open source project to contribute to :sweat_smile:, nothing else. I'm still learning React & Redux, and I was checking out your repo and noticed the recent migration to Yarn, and noticed that the existence of `package-lock.json` the examples dir showed the migration was not completed, so I decided to try to complete it.

**Comment by markerikson** [comment]
Ah, gotcha.

Yeah, there's an issue from _3 years ago_ I had filed saying "we really ought to rewrite the examples":

- https://github.com/reduxjs/redux/issues/3917

and then not much happened with it.

Honestly, the main things we could use help with atm are docs, across all 3 of our repos:

- https://www.youtube.com/watch?v=rPJmnxDX9lY

as well as testing of the beta versions of our libs in various environments as we work towards the upcoming major releases.

**Comment by mWaldbaur** [comment]
Okay, I'll try to contribute towards that too, but I think this PR could serve as a good starting point, because it simplifies the way examples are handled (Through the package manager instead of custom scripts), so future improvements can build on top of these cleanups.

If you think this doesn't make sense, I can close this PR :smiley: and focus more on other doc improvements in the future.

**Pull request closed without merging**
